name: Deploy to Surge

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Surge
        run: npm install --global surge

      - name: Deploy to Surge
        run: surge ./ https://surgeappoen.surge.sh/ --token ${{ secrets.SURGE_TOKEN }}
